### ISSUE TITLE
Slack Deprecating TLS v1.0 and v1.1

### ISSUE THREAD

**Issue by bouvet-itdrift** [MelonSmasher/Momentum#5]
I'm getting a warning about Momentum using older versions of TLS.

"On March 4, 2020, we'll require all communications with Slack to use TLS version 1.2 or greater. Using TLS version 1.2 or greater makes Slack safer for everyone. In advance of this, we'll implement a 24-hour test deprecation on February 19, 2020."

https://api.slack.com/changelog/2019-07-deprecate-early-tls-versions

**Comment by grubee** [comment]
Same, any chance to update code to use TLS v1.2?

**Comment by WiZaRd31337** [comment]
Hi @MelonSmasher I've pushed PR with simple patch to support TLS 1.2

**Comment by acomadmin** [comment]
This deprecation is a breaking change @MelonSmasher. Any chance you can approve @WiZaRd31337's PR or push out an update to address the issue?

Otherwise is anyone aware of a more actively developed (open source) solution for Veeam Slack alerts?

**Comment by kylehemker** [comment]
This Slack deprecation is a breaking change @MelonSmasher. Any chance you can approve @WiZaRd31337's PR or push out a fix yourself?

Otherwise is anyone aware of a more actively developed (open source) solution for Veeam Slack alerts?

**Comment by WiZaRd31337** [comment]
@kylehemker @grubee @bouvet-itdrift Guys, you can try the fixed version from my repo till waiting for a reaction from the author @MelonSmasher

**Comment by MelonSmasher** [comment]
@WiZaRd31337 I've merged #6.

**Comment by MelonSmasher** [comment]
I've published updated installer packages in the [latest release (v0.0.2.0)](https://github.com/MelonSmasher/Momentum/releases/tag/v0.0.2.0).
